= FUnicorn Library Arduino-compatible =

This library is used with the FUnicorn irreverent educational desk gadget by Alpenglow Industries.  Simply put, the FUnicorn is the most majestic way of telling someone off.  From it's gold rearing form to its classy cursive script, recipients of its special message will be stunned by its glory and know that you truly care.

Check it out at: https://www.alpenglowindustries.com/funicorn
Or visit us at: www.alpenglowindustries.com

This library was written in standard C, so it might look at little intimidating if you've only worked in Arduino C.  Do not fear, the unicorn does not bite.  There are many shortcut definitions already set up for you to use, look at FUnicorn.h for more details.  There are also functions for example blinking patterns, we encourage you to take them as a starting point and write your own!


================================================================================

MIT License:

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

==================================================================================
